"""WebSocket protocol envelopes for wrangler ↔ api traffic.

Both directions use a discriminated union keyed on "kind". JSON on the wire,
one message per WS frame. Request/response correlation uses a uuid4
`request_id` generated by api.
"""

from __future__ import annotations

from typing import Annotated, Literal

from pydantic import BaseModel, ConfigDict, Field

from wrangled_contracts.commands import Command  # noqa: TC001
from wrangled_contracts.wled import WledDevice  # noqa: TC001


class _Frozen(BaseModel):
    model_config = ConfigDict(frozen=True)


# PushResult was previously a local type in apps/wrangler/pusher.py.
# Hoisted here to serve as the single cross-process source of truth.
class PushResult(_Frozen):
    """Outcome of a single command push to a WLED device."""

    ok: bool
    status: int | None = None
    error: str | None = None


# Wrangler → api --------------------------------------------------------


class Hello(_Frozen):
    kind: Literal["hello"] = "hello"
    wrangler_id: str = Field(min_length=1, max_length=64)
    wrangler_version: str
    devices: list[WledDevice]


class DevicesChanged(_Frozen):
    kind: Literal["devices_changed"] = "devices_changed"
    devices: list[WledDevice]


class CommandResult(_Frozen):
    kind: Literal["command_result"] = "command_result"
    request_id: str
    result: PushResult


class StateSnapshot(_Frozen):
    kind: Literal["state_snapshot"] = "state_snapshot"
    request_id: str
    mac: str
    state: dict | None = None
    error: str | None = None


class SetDeviceNameResult(_Frozen):
    kind: Literal["set_device_name_result"] = "set_device_name_result"
    request_id: str
    device: WledDevice | None = None
    error: str | None = None


class Pong(_Frozen):
    kind: Literal["pong"] = "pong"


WranglerMessage = Annotated[
    Hello | DevicesChanged | CommandResult | StateSnapshot | SetDeviceNameResult | Pong,
    Field(discriminator="kind"),
]


# api → wrangler -------------------------------------------------------


class Welcome(_Frozen):
    kind: Literal["welcome"] = "welcome"
    server_version: str


class RelayCommand(_Frozen):
    kind: Literal["command"] = "command"
    request_id: str
    mac: str
    command: Command


class GetState(_Frozen):
    kind: Literal["get_state"] = "get_state"
    request_id: str
    mac: str


class Rescan(_Frozen):
    kind: Literal["rescan"] = "rescan"


class SetDeviceName(_Frozen):
    kind: Literal["set_device_name"] = "set_device_name"
    request_id: str
    mac: str
    name: str = Field(min_length=1, max_length=32)


class Ping(_Frozen):
    kind: Literal["ping"] = "ping"


ApiMessage = Annotated[
    Welcome | RelayCommand | GetState | Rescan | SetDeviceName | Ping,
    Field(discriminator="kind"),
]
